Tensor is N-D representation of array data of various ranks, scalar ranks - 0, Vector rank - 1, matrix rank - 2, and higher dimentionality.

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

**tf.constant**

* This is immutable

In [3]:
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
const_1 = tf.constant(127)

In [5]:
const_1

<tf.Tensor: shape=(), dtype=int32, numpy=127>

In [6]:
const_1.numpy()

127

In [7]:
const_1.dtype

tf.int32

In [8]:
# Vector

const_2 = tf.constant([2, 3, 4, 5, 6, 7], dtype = 'int8')

In [9]:
print(const_2.numpy())

[2 3 4 5 6 7]


In [10]:
const_3 = tf.constant([10.0, 20, 30, 40.0, 50, 60], dtype = 'float16')

In [11]:
print(const_3)

tf.Tensor([10. 20. 30. 40. 50. 60.], shape=(6,), dtype=float16)


In [12]:
#matrix representation 

const_4 = tf.constant([[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]], dtype = 'float16')

In [13]:
print(const_4)

tf.Tensor(
[[10. 20. 30. 40. 50. 60.]
 [10. 20. 30. 40. 50. 60.]
 [10. 20. 30. 40. 50. 60.]], shape=(3, 6), dtype=float16)


In [14]:
const_5 = tf.constant([[[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
                      [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
                      [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]]], dtype = 'float16')

In [15]:
print(const_5)

tf.Tensor(
[[[10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]]

 [[10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]]

 [[10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]
  [10. 20. 30. 40. 50. 60.]]], shape=(3, 3, 6), dtype=float16)


In [16]:
const_6 =   tf.constant([[[[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]]],
            [[[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]]],
            [[[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]],
            [[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60],[10.0, 20, 30, 40.0, 50, 60]]]])


In [17]:
print(const_6)

tf.Tensor(
[[[[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]]


 [[[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]]


 [[[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]

  [[10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]
   [10. 20. 30. 40. 50. 60.]]]], shape=(3, 3, 3, 6), dtype=float32)


In [18]:
# int8 is 8 bit range from -128 to 127

const_7 = tf.constant([100, -15, -128, 0, 10], dtype = 'int8')

In [19]:
print(const_7)

tf.Tensor([ 100  -15 -128    0   10], shape=(5,), dtype=int8)


In [21]:
# Tensor Rank 3

tf.constant([[[10.0, 20, 30, 40.0, 50, 60],
              [10.0, 20, 30, 40.0, 50, 60],
              [10.0, 20, 30, 40.0, 50, 60]],
             
            [[10.0, 20, 30, 40.0, 50, 60],
             [10.0, 20, 30, 40.0, 50, 60],
             [10.0, 20, 30, 40.0, 50, 60]]])

<tf.Tensor: shape=(2, 3, 6), dtype=float32, numpy=
array([[[10., 20., 30., 40., 50., 60.],
        [10., 20., 30., 40., 50., 60.],
        [10., 20., 30., 40., 50., 60.]],

       [[10., 20., 30., 40., 50., 60.],
        [10., 20., 30., 40., 50., 60.],
        [10., 20., 30., 40., 50., 60.]]], dtype=float32)>

**tf.variable**

* This is mutable

In [24]:
var_1 = tf.Variable(0, dtype = 'float16')

In [25]:
print(var_1)

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=0.0>


In [26]:
import numpy as np

x = np.zeros(shape =(3, 2, 2))

In [29]:
#Ttpecasting numpy into Tensor

x_tensor = tf.Variable(x)

In [30]:
display(x_tensor)

<tf.Variable 'Variable:0' shape=(3, 2, 2) dtype=float64, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])>

**Mathematical Operation**

In [39]:
X =tf.constant([[3, 5, 10, 11]], dtype ='float32')

In [40]:
display(X)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 3.,  5., 10., 11.]], dtype=float32)>

In [41]:
Weights = tf.Variable([[10],
                       [20],
                       [12],
                       [10]], dtype ='float32')

In [42]:
display(Weights)

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[10.],
       [20.],
       [12.],
       [10.]], dtype=float32)>

In [45]:
tf.tensordot(X, Weights, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[360.]], dtype=float32)>

In [46]:
# W.X

tf.tensordot(Weights, X, axes=1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 30.,  50., 100., 110.],
       [ 60., 100., 200., 220.],
       [ 36.,  60., 120., 132.],
       [ 30.,  50., 100., 110.]], dtype=float32)>

In [47]:
#Zero Matrix using tf

tf.zeros(shape=(3,3), dtype = tf.float32, name = 'Zero Matrix')

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [49]:
# Ones Matrix using tf

tf.ones(shape=(3,3), dtype='float32', name='ones matrix')

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [50]:
# create a tensor with constant value and dimentions

tf.fill(dims=(3,4), value = 8)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]], dtype=int32)>

In [57]:
# It will be used to generate smaples for a vector shape in b/w start value and stop value

tf.linspace(start = 0, stop = 200, num = 10, name ='None')

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])>

In [58]:
# Delta = 3 i.e. spacing b/w two no.s

tf.range(start=10, limit = 30, delta=3)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([10, 13, 16, 19, 22, 25, 28], dtype=int32)>

**Keras - Api of Tensorflow**

In [63]:
import keras

In [64]:
# Dense Layer in NN
from keras.layers import Dense
# Feed Foreward NN
from keras.models import Sequential
# Model Optimizers
from keras.optimizers import RMSprop

In [65]:
def build_model():
  model = Sequential()
  
  # units = Number of Neurons in each layer, activation = 'relu', input_shape = number of input columns in data
  model.add(Dense(units = 64, activation = 'relu', input_shape = [3]))
  # Output Layer
  model.add(Dense(units = 1))

  model.compile(optimizer = 'RMSProp', metrics = ['mean_squared_error'])
  return model

In [66]:
model = build_model()

In [68]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                256       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________
